version: '3.4'

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.1"
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      ELASTIC_PASSWORD: 'password'
    volumes:
      - type: bind
        source: "."
        target: /usr/share/elasticsearch/data
    deploy:
      replicas: 1

  logstash:
    image: "docker.elastic.co/logstash/logstash:6.2.1"
    environment:
      CONFIG_RELOAD_AUTOMATIC: 'true'
    ports:
      - 5000:5000
      - 5000:5000/udp
    # volumes:  # TODO: needs accepting TCP in logstash.conf
    #   - ":/usr/share/logstash/pipeline:ro"
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'  # docker internal
      SERVER_NAME: "localhost"
    deploy:
      replicas: 1

  logspout:
    image: logspout-tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      ROUTE_URIS: "logstash+tcp://logstash:5000"
    deploy:
      replicas: 1
